server:
  port: 8081
  servlet:
    context-path: /dev

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/blogs_dev?useUnicode=true&charcterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
