spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      # ???true
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    client-type: jedis
    host: 127.0.0.1
    port: 6379
    password:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: false

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: countSql
  reasonable: true

logging:
  config: classpath:logback.xml

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.tzvtc.entity
  configuration:
    map-underscore-to-camel-case: true

minio:
  endpoint: http://127.0.0.1:9000 #Minio服务所在地址
  bucketName: blog #存储桶名称
  accessKey: hurdjay #访问的key
  secretKey: hcj123123 #访问的秘钥