server:
  port: 8081
  servlet:
    context-path: /dev

spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/blogs_dev?useUnicode=true&charcterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: hurdjay
    password: huchengjie0815
